CXXFLAGS = --std=c++17 $(INCLUDES)
CXX = g++

vector: random.cpp
	$(CXX) $(CXXFLAGS) random.cpp vector.h vector.cpp -o main.out

list: random.cpp 
	$(CXX) $(CXXFLAGS) random.cpp list.h list.cpp -o main.out