CXXFLAGS = --std=c++17 $(INCLUDES)
CXX = g++

vector: random.cpp
	$(CXX) $(CXXFLAGS) random.cpp -O0 vector.h vector.cpp -o v.out

list: random.cpp 
	$(CXX) $(CXXFLAGS) random.cpp -O0 cll.h cll.cpp -o l.out